// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxRQqRfVOyYpYxxZ1SXSo2qFysGmY6BXA',
    appId: '1:17641739017:web:552685e1d4ead8f996b9d8',
    messagingSenderId: '17641739017',
    projectId: 'gharsaz-e77e7',
    authDomain: 'gharsaz-e77e7.firebaseapp.com',
    storageBucket: 'gharsaz-e77e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Bb96RiIms9B-HzvhinCr7mZln7kdYCo',
    appId: '1:17641739017:android:658168e7dda3bdf696b9d8',
    messagingSenderId: '17641739017',
    projectId: 'gharsaz-e77e7',
    storageBucket: 'gharsaz-e77e7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxRQqRfVOyYpYxxZ1SXSo2qFysGmY6BXA',
    appId: '1:17641739017:web:1eb8d9817379616296b9d8',
    messagingSenderId: '17641739017',
    projectId: 'gharsaz-e77e7',
    authDomain: 'gharsaz-e77e7.firebaseapp.com',
    storageBucket: 'gharsaz-e77e7.firebasestorage.app',
  );
}
